name: Auto upgrade dependencies with uv

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 6 * * 1'  

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  

      - name: Install uv
        run: pip install uv

      - name: Upgrade dependencies
        run: uv pip upgrade

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add pyproject.toml
          git diff --cached --quiet || git commit -m "chore(deps): upgrade dependencies via uv"
          git push